<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <RootNamespace>ToInfinity.Protocol</RootNamespace>
    <AssemblyName>ToInfinity.Protocol</AssemblyName>
  </PropertyGroup>

</Project>
