<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <RootNamespace>ToInfinity.ClientViewer</RootNamespace>
    <AssemblyName>ToInfinity.ClientViewer</AssemblyName>
    <Platforms>x64</Platforms>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\protocol\csharp\ToInfinity.Protocol\ToInfinity.Protocol.csproj" />
  </ItemGroup>

</Project>
